version: '3.9'
services:
  database:
    image: 'postgres:15-alpine'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=riot
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
  db-test:
    image: 'postgres:15-alpine'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=riot
    ports:
      - 5434:5432
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
